### ISSUE TITLE
Error on BasiqSDK.Session

### ISSUE THREAD

**Issue by Artem-Klyuev** [basiqio/basiq-sdk-nodejs#9] opened 2019-02-07 13:08 UTC
This string gives an error
`const session = await BasiqSDK.Session("YOUR_API_KEY");
`
Error
` TypeError: Cannot read property 'reduce' of undefined `
`/node_modules/basiq-sdk-nodejs/dist/index.js:1:3325)
`

I have the latest version.

**Comment by vabtrix** [comment] 2019-02-08 04:56
Similar Issue at my end as well: 
TypeError: Cannot read property 'reduce' of undefined
    at new n (/srv/node_modules/basiq-sdk-nodejs/index.js:1:12220)
    at Request._callback (/srv/node_modules/basiq-sdk-nodejs/index.js:1:11914)
    at Request.self.callback (/srv/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/srv/node_modules/request/request.js:1161:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/srv/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:313:30)

**Comment by vaishali-bluepineapple** [comment] 2019-02-08 05:00
Serach for "oauth2/token" in "dist/index.js" of this node module and replace this path with "token". This will fix TypeError: Cannot read property 'reduce' of undefined.

**Comment by vabtrix** [comment] 2019-02-11 05:47
That does not seem to fix the issue @vaishali-bluepineapple

**Comment by aterentic-basiq** [comment] 2019-02-11 09:46
@vabtrix , @Artem-Klyuev , @vaishali-bluepineapple , this is caused by removing /oauth/token endpoint from production as it is deprecated for a while, sorry for inconveniences. Issue in SDK is fixed (thanks @vaishali-bluepineapple) and on npm (version 1.1.1.).

**Comment by aterentic-basiq** [comment] 2019-02-12 09:18
@Artem-Klyuev , I'll close issue as it is fixed in 1.1.1 version.

**Closed by aterentic-basiq** 2019-02-12 09:18 UTC
